<a href="https://colab.research.google.com/github/HarshrajSharma/DataAnalytics/blob/main/DataAnalyticsDay4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Day4**

In [ ]:
#Create a list 


y=('Apple',2,3,4) #Tuple: Can keep different types of elements
z=[1,2,3,4] #List: Can keep only same types of elements

print(type(y))
print(type(z))

<class 'tuple'>
<class 'list'>


In [ ]:
myList=[]
myTuple=()

for i in range(0, 1000000):
  myList.append(i)
  myTuple.append(i)

print(myList)
print(myTuple)

In [ ]:
#Inbuilt functions for lists

myList=list(range(0, 1000)) #list(range(0,345)) will create a list with sequential data
print(myList)

myTuple=tuple(range(0, 1000)) #tuple(range(0,345)) will create a list with sequential data
print(myTuple)

#Tuple used less memory than list for the same data
#List is mutable whereas Tuple is immutable


In [ ]:
import sys, platform,time

myList=list(range(0, 100000))
#myList[4]=1001  #Mutable

myTuple=tuple(range(0, 100000))
#myTuple[4]=5001 #Immutable

print('List memory: ',sys.getsizeof(myList))
print('Tuple memory: ', sys.getsizeof(myTuple))

start=time.time_ns()
for i in range(0, len(myList)):
  a=myList[i]
end=time.time_ns()
print('Total time for list:', end- start)

start=time.time_ns()
for i in range(0, len(myTuple)):
  a=myTuple[i]
end=time.time_ns()
print('Total time for tuple:', end- start)

In [ ]:
myList=list(range(0, 1000))
squareList=[]

print(myList[4:]) #Prints from 4 to the last element in the list


for i in myList:
  squareList.append(i**2)

print(squareList)


[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 2

In [ ]:
#Find an element 22 in the list
myList=list(range(0, 11))
myList[4]=56
print(myList)

print(myList.index(56)) # .index() will give the index of the element if it is present in the list
myList.remove(2)
print(myList)


[0, 1, 2, 3, 56, 5, 6, 7, 8, 9, 10]
4
[0, 1, 3, 56, 5, 6, 7, 8, 9, 10]


In [ ]:
#Remove all the elements from the third positionto last in a list

myList=list(range(0,11))
print(myList)

del myList[2:] #Delete all the elements from 3rd position to the last
print(myList)

myList.pop(1) #Pops the element at position 0 in the list
print(myList)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 1]
[0]


In [ ]:
#Sort function
myList=[5,8,6,1,2,3,4,8,9,6,5,2,3,11]
print(myList)
myList.sort()
print(myList)

[1, 2, 2, 3, 3, 4, 5, 5, 6, 6, 8, 8, 9, 11]


In [ ]:
#String library
import string, random

z=string.ascii_letters
y=string.digits
x=string.punctuation
w=random.sample(z,6)
v=random.choice(z)


print(z)
print(y)
print(x)
print(w)
print(v)

random.shuffle(w)
print(w)

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['T', 'h', 'V', 'S', 'J', 'l']
f
['l', 'J', 'T', 'h', 'V', 'S']


In [ ]:
#Generate a random password of length 10 such that 2 letters are upper case , 1 is a digit, 1 is a special character next find if @ is there in the password or not.
#If not then replace the third character with @

import string, random
def generatePassword():
  password=''

  upCase=random.sample(string.ascii_uppercase, 2)
  upCase=''.join(upCase)

  digits=random.choice(string.digits)

  specialChar=random.choice(string.punctuation)
  
  lowerCase=random.sample(string.ascii_lowercase, 6)
  lowerCase=''.join(lowerCase)

  password=digits+specialChar+upCase+lowerCase
  if(password.find('@')==1):
    return password
  else:
    #Pending: if the third character is the only digit or special character then it will be replaced
    password=password[0:2]+'@'+password[3:]
    print('Password: ', password)
    
    return password

def main():
  print('Generating Password....')
  generatePassword()

main()
  


Generating Password....
Password:  9^@Mpaimtk


### **Numpy**

In [ ]:
from numpy.core.memmap import dtype
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(arr.shape) #Print (5, ) show the number of rows and columns
print(arr.ndim)  #Prints the dimension of the array
print(arr.size)

arr1=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1)
print(arr1.dtype)
print(arr1.shape) #Print (2,5) show the number of rows and columns
print(arr1.ndim)  #Prints the dimension of the array
print(arr1.size)

arr1=np.zeros((5,6))  #Fills all the element with zeros
print(arr1)

arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]], dtype='float')
print('Array:\n', arr2)

arr3=np.arange(0,30,5)
print(arr3)

arr4=np.random.random((2,4))
print(arr4)

arr6=np.array([2,4,6,8,9,11])
print(arr6.ndim)
newArr=arr6.reshape(2,3)
print(newArr)

#printing array
for i in newArr:
  for j in i:
    print('The elements are:', j)

arr7=np.array([1,2,3,4,5])
arr8=np.array([6,7,8,9,10])
arr9=np.concatenate((arr7, arr8)) #Arrays shoud be in same dimension
print(arr9)

x=np.where(newArr==4)
print(x)

#Create a 2D array the array should have sequence of numbers from 1 to 30 with a step jump of 3 and find out all the even number sin the 2d array

newArray=np.array([])
pos=0
for i in range(1,31,3):
  print(i)
  
  pos+=1
#newArray=newArray.reshape(2,5)
print(newArray)

[1 2 3 4 5]
int64
(5,)
1
5
[[1 2 3 4 5]
 [1 2 3 4 5]]
int64
(2, 5)
2
10
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Array:
 [[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]
[ 0  5 10 15 20 25]
[[0.27824903 0.8077589  0.01666621 0.89807282]
 [0.42023673 0.36864093 0.98303572 0.92752663]]
1
[[ 2  4  6]
 [ 8  9 11]]
The elements are: 2
The elements are: 4
The elements are: 6
The elements are: 8
The elements are: 9
The elements are: 11
[ 1  2  3  4  5  6  7  8  9 10]
(array([0]), array([1]))
1
4
7
10
13
16
19
22
25
28
[]


In [ ]:
from numpy import random

x=random.randint(100)
print(x)
for i in range(3,100):
  x=random.randint(1000)

y=random.rand(5)
print(y)

speed=[112,80,40,45,78, 78]
x=np.std(speed)
y=np.median(speed)
#z=np.mode(speed,35)
w=np.percentile(speed, 75)

print(x)
print(y)
#print(z)
print(w)


97
[0.77627815 0.17252948 0.02707909 0.88357626 0.38331563]
24.11373513627083
78.0
79.5


### **Home Assignment**

In [ ]:
#1)Find the square of each element in the list.

myList=list(range(0, 11))
squareList=[]


for i in myList:
  squareList.append(i**2)

print(squareList)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#2)Generate a random Password which meets the following conditions
  #a)Password length must be 10 characters long.
  #b)It must contain at least 2 upper case letters, 1 digit, and 1 special symbol.
  #c)Next, create a list with those and find whether @ is there, if not replace the third position with @
  #d) print the list as a single string with join() function



#Generate a random password of length 10 such that 2 letters are upper case , 1 is a digit, 1 is a special character next find if @ is there in the password or not.
#If not then replace the third character with @

import string, random
def generatePassword():
  password=''

  upCase=random.sample(string.ascii_uppercase, 2)
  upCase=''.join(upCase)

  digits=random.choice(string.digits)

  specialChar=random.choice(string.punctuation)
  
  lowerCase=random.sample(string.ascii_lowercase, 6)
  lowerCase=''.join(lowerCase)

  password=digits+specialChar+upCase+lowerCase

  #print('Initial', password)
  if(password.find('@')==1):
    return password
  else:
    #Pending: if the third character is the only digit or special character then it will be replaced
    password=password[0:2]+'@'+password[3:]
    #print('Password: ', password)
    
    return password

def main():
  print('Generating Password....')
  print(generatePassword())

main()

Generating Password....
6*@Luynzbv


In [ ]:
#3)a)Use Numpy to create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

import numpy as np

#print("Creating 5X2 array using numpy.arange")
sampleArray = np.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [ ]:
#b)Use Numpy to create an array of 5*5 floating point values. Return array of odd kkrows and even columns from below numpy array





In [ ]:
import numpy as np

def authenticate(userId, userPassword):
  auth=np.array([['admin1','admin2','admin3','admin4','admin5'],['admin1','admin2','admin3','admin4','admin5']])
  #print(auth[1][1])

  id=['admin1','admin2','admin3','admin4','admin5']
  password=['admin1','admin2','admin3','admin4','admin5']

  for i in range(0, 5):
    
    if(userId==id[i] and userPassword==password[i]):
      return 1

def main():
  username=input("Enter username:")
  password=input("Enter password:")

  if(authenticate(username, password)==1):
    print('Logged in successfully!')
  else:
    print('Invalid Login!')

main()

Enter username:admin1
Enter password:admin1
admin2
Logged in successfully!
